# -*- coding: utf-8 -*-
"""Python DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OXahDPg_UkqB81Vtv_201050mgxPwSP
"""

data ={
    'id':1,
    'name':'user-1',
    'scors':[10,20,30],
    'active':True
}
userid = data.get('id')
#userid
role =data.setdefault('role','student')
#data
data.update({
    'active':False,
    'total':sum(data['scors'])
})
#data
if data['total'] > 40:
  data['status']='Passed'
else:
  data['status']='Fail'
#data
result=[]
for k,v in data.items():
  result.append((k,v))

#data,result
copydata= data.copy()
#copydata
data['scors'].append(2)
#copydata
removerole=copydata.pop('role')
last=copydata.popitem()
data,result,copydata,removerole,last

#create two list by using range then find even and odd by using list comprehension and without function

num=list(range(10))
num1=list(range(20))
even=set([ x for x in num if x%2==0 ]+[ y for y in num1 if y%2==0])
odd=set([ x for x in num if x%2!=0 ]+[ y for y in num1 if y%2 !=0])
print("Even:",even)
print("Odd:",odd)

def eve(num1,num2):
  return set([ x for x in num1 if x%2==0 ]+[ y for y in num2 if y%2==0])

def od(num1,num2):
  return set([ x for x in num1 if x%2!=0 ]+[ y for y in num2 if y%2 !=0])


num=list(range(10))
num1=list(range(20))
print("Even:" ,eve(num,num1))
print("Odd:",od(num,num1))

def binary(arr,n):
  low=0
  high=len(arr)-1
  while low<=high:
    mid=(low+high)//2
    if arr[mid]==n:
      return mid
    elif arr[mid]<n:
      low=mid+1
    else:
      high=mid-1
  return -1



arr= list(range(20))
print("Index of value:", binary(arr,21))

def bi_search(array,value):
  low,high=0,len(array)-1
  while low<=high:
    mid= (low+high)//2
    if array[mid]==value:
      return mid
    elif array[mid]<value:
      low=mid+1
    else:
      high=mid-1
  return -1

array=list(range(30))
print("Index of value:",bi_search(array,4))

def binary_search(arr,val):
  low,high=0,len(arr)-1
  while low<=high:
    mid=(low+high)//2
    if arr[mid]==val:
      return mid
    elif arr[mid]<val:
      low=mid+1
    else:
      high=mid-1
  return -1

array=list(range(30))
print("index of value:",binary_search(array,5))

def merge_sort(arr):
   if len(arr)<= 1:
      return arr
   mid=len(arr)//2
   lt=merge_sort(arr[:mid])
   rt=merge_sort(arr[mid:])
   return merge(lt,rt)

def merge(lt,rt):
  out=[]
  left_index=right_index=0
  while left_index <len(lt) and right_index<len(rt):
    if lt[left_index] < rt[right_index]:
        out.append(lt[left_index])
        left_index +=1
    else:
       out.append(rt[right_index])
       right_index +=1

  out.extend(lt[left_index:])
  out.extend(rt[right_index:])
  return out

arr=[3,8,1,9,5,7]
print("Sorted array:",merge_sort(arr))

def merge_sort(arr):
  if len(arr)<=1:
    return arr
  mid=len(arr)//2
  lt=merge_sort(arr[:mid])
  rt=merge_sort(arr[mid:])
  return merge(lt,rt)

def merge(lt,rt):
  out=[]
  i=j=0
  while i<len(lt) and j<len(rt):
    if lt[i] <= rt[j]:
      out.append(lt[i])
      i +=1
    else:
      out.append(rt[j])
      j +=1

  out.extend(lt[i:])
  out.extend(rt[j:])
  return out

arr=[3,7,1,2,9,8]
print(merge_sort(arr))

def merge_sort(arr):
  if len(arr) <= 1:
    return arr
  mid = len(arr)//2
  left=merge_sort(arr[:mid])
  right=merge_sort(arr[mid:])
  return merge(left,right)

def merge(left,right):
    result=[]
    i=j=0

    while i<len(left) and j<len(right):
      if left[i] <= right[j]:
        result.append(left[i])
        i +=1
      else:
        result.append(right[j])
        j +=1

    result.extend(left[i:])
    result.extend(right[j:])
    return result

arr=[9,8,7,6,5]
print(merge_sort(arr))

arr=[8,7,9,3,4,5]
n=len(arr)

for i in range(n-1):
  #idx=i
  for j in range (i+1,n):
    if arr[j]<arr[i]:
      temp =arr[i]
      arr[i]=arr[j]
      arr[j]=temp

print(arr)

def merge_sort(arr):
  if len(arr) <=1:
    return arr
  mid=len(arr)//2
  left=merge_sort(arr[:mid])
  right=merge_sort(arr[mid:])
  return merge(left,right)

def merge(left,right):
  result=[]
  i=j=0
  while i<len(left) and j<len(right):
     if left[i] <= right[j]:
      result.append(left[i])
      i += 1
     else:
      result.append(right[j])
      j +=1

  result.extend(left[i:])
  result.extend(right[j:])
  return result

arr=[9,8,6,5,4]
print(merge_sort(arr))

d= { "a":1,"b":2}

data ={
    'name':'maisha',
    'id':106,
    'active':True,
    'scores':[75,88,89],
    'cgpa':3.84
}
userid=data.get('id')
role = data.setdefault('role','student')
data.update({
    'active':False,
    'total':sum(data['scores'])
})
if data['total'] <300:
  data['status']='Do better'
else:
  data['status']='Best'

result=[]
for k,v in data.items():
  result.append((k,v))

copydata=data.copy()
data['scores'].append(82)

removeelement= copydata.pop('role')
lastelement=copydata.popitem()

data,result,copydata,removeelement,lastelement

d = {"a":1,"b":2}
x=d.pop("c",None)
print("Popped c :",x)
print("Remaining:",d)

s=" 2025-10-17"
x,y,z=s.split('-')
print(x,y,z)

coords_tuple=(1,2,3)
coords_list=list(coords_tuple)
coords_list.append(4)
coords_tuple2 =tuple(coords_list)
print("Original Tuple:",coords_tuple)
print("Modified Tuple:",coords_tuple2)

A= {1,2,3,4,5}
B={4,5,6,7}
def set_operation(a,b):
  return{
      'union': a|b,
      'intersection': a&b,
      'a_minus_b':a-b,
      'b_minus_a':b-a,
      'symmetric_diff': a^b

  }
print("Operations:",set_operation(A,B))

def fact(n):
  if n<= 1:
    return 1
  return n*fact(n-1)
print(fact(5))

from collections  import Counter
items =["apple","banana","apple","orange","banana","apple"]
c=Counter(items)
print("Most common:",c.most_common(2))
print("Counts:",dict(c))

def  chunks(lst,n):
  for i in range(0,len(lst),n):
    yield lst[i:i+n]
print(list(chunks(list(range(10)),3)))

from itertools import zip_longest
matrix=[[1,2,3],[4,5],[6]]
transposed=[list(filter(lambda x:x is not None,row)) for row in zip_longest(*matrix)]
print(transposed)

def make_list(n):
  return [i for i in range(n)]
def make_gen(n):
  for i in range(n):
    yield i

print("First 5 from gen:",[x for x in make_gen(5)])
print("List 5:",make_list(5)[:5])

a ={'x':1,'y':2}
b={'y':3,'z':4}

def merge_sum(a,b):
  res =dict(a)
  for k,v in b.items():
    if k in res and isinstance(res[k],(int,float)) and isinstance(v,(int,float)):
      res[k] += v
    else:
      res[k] = v
  return res

print("Merged:",merge_sum(a,b))

def gen_squares(n):
  return (i*i for i in range(n))

g = gen_squares(10)
print("First three:",[next(g) for _ in range (3)])
print("Remaining sum:",sum(g))

def matmul(A,B):
  return [[sum (a*b for a,b in zip(row,col)) for col in zip(*B)]for row in A]

A=[[1,2],[3,4]]
B=[[5,6],[7,8]]
print(matmul(A,B))

def log_calls(fn):
  def wrapper(*args,**kwargs):
    print(f"calling {fn.__name__}")
    return fn(*args,**kwargs)
  return wrapper

@log_calls
def greet(name):
  return f"Hello {name}"

print(greet('world'))

import re
text ="al b23 c456"
print(re.findall(r"\d+",text))

data =[("a",1),("b",2),("a",2),("b",3)]
d={}
for k,v in data:
  d.setdefault(k,set()).add(v)
print(d)

def merge(*lst):
  seen =set()
  out=[]
  for li in lst:
    for x in li:
      if x not in seen:
        seen.add(x)
        out.append(x)
  return out

print(merge([1,2,3],[3,4],[2,5]))

from collections import defaultdict
pairs=[("a",1),("b",2),("a",3),("b",4)]
grouped = defaultdict(list)
for k,v in pairs:
  grouped[k].append(v)

print("Grouped:",dict(grouped))

from collections import Counter

data =[1,2,2,3,3,3]
c=Counter(data)
total =sum(c.values())
prob={k:v/total for k,v in c.items()}
print(prob)

words =["banana","fig","apple","cherry"]
sorted_words= sorted(words,key=lambda w: (len(w),w))
print(sorted_words)

from functools import reduce
nums=[1,2,3,4,5]
squares=list(map(lambda x: x*x,nums))
evens=list(filter(lambda x: x%2==0,nums))
sum_vals=reduce (lambda a,b:a+b,nums)

print(squares)
print(evens)
print(sum_vals)

def  printer(*args,**kwargs):
  print("ARGS:",args)
  print("KW:",kwargs)
printer(1,2,3,a=10,b=20)

args =["--name","Alic","--age","30"]
it =iter(args)
parsed={}
for a in it:
  if a.startswith("--"):
    parsed[a.lstrip("-")] = next(it,None)

print(parsed)

import random
items = list(range(10))
print("sample 3:",random.sample(items,3))
print("shuffle copy:",random.sample(items,len(items)))

data ={"user":{"name":"sam","roles": ["admin","user"]},"active":True}

def has_role(d,role):
  return role in d.get("user",{}).get("roles",[])
print("Is admin?",has_role(data,"admin"))
print("Is moderator?",has_role(data,"moderator"))

def binary_search(a,x):
  lo,hi=0,len(a)-1
  while lo<=hi:
    mid=(lo+hi)//2
    if a[mid] ==x:
      return mid
    if a[mid] <x:
      lo =mid+1
    else:
      hi=mid-1
  return -1

arr=[1,3,5,7,9]
print(binary_search(arr,5),binary_search(arr,2))

from contextlib import contextmanager
@contextmanager
def simple_cm():
  print("enter")
  try:
    yield
  finally:
    print("exit")

with simple_cm():
  print("inside")

matrix =[[1,2,3],[4,5,6],[7,8,9]]
def transpose(m):
  return [list(row) for row in zip(*m)]
print("transposed:",transpose(matrix))

def append_to(value,lst=None):
  if lst is None:
    lst=[]
  lst.append(value)
  return lst

print(append_to(1))
print(append_to(2))

def validate_person(p):
  return isinstance(p.get("name"),str) and isinstance(p.get("age"),int)

print(validate_person({"name":"tom","age":30}))
print(validate_person({"name":"tom","age":30}))

words =["  hello","world  ","  from","python "]
clean={w.strip().upper() for w in words}
sentence = " ".join(clean)

print(clean)
print(sentence)
print(sentence.split())

def merge_config(*configs):
  res={}
  for cfg in configs:
    res.update(cfg)
  return res
print(merge_config({'a':1,'b':2},{'b':3},{'c':4}))

items = [3,"apple",1,"banana",2]
nums = sorted(x for x in items if isinstance (x,int))
strs = sorted(x for x in items if isinstance (x,str))
combine =nums + strs
print(combine)

headers={"content-Type":"text/plain", "Accept":"*/*"}
normalize= {k.lower(): v for k,v in headers.items()}
print(normalize.get("content-type"))

t =(1,[2,3],4)
t[1].append(5)
print(t)

line="name,age,city"
data=[s.strip() for s in line.split(",")]
print("Columns:",data)

def partition(lst,pred):
  tr,fl=[],[]
  for x in lst:
    (tr if pred(x) else fl).append(x)
  return tr,fl

print(partition(range(10),lambda x:x%2==0))

def safe_div(a,b):
  try:
    return a/b
  except ZeroDivisionError:
    return None
  finally:
    pass
print("10/2",safe_div(10,2))
print("10/0",safe_div(10,0))

def is_pal(s):
  s2=''.join(ch.lower() for ch in s if ch.isalnum())
  return s2==s2[::-1]

print(is_pal("A man a plan a canal panama"))

from ast import literal_eval

expr="[1,2,3]"
print(literal_eval(expr))

word=["apple","banana","cherry"]
def freq_per_word(words):
  result={}
  for w in word:
    d={}
    for ch in w:
      d[ch]=d.get(ch,0)+1
    result[w]=d
  return result

print(freq_per_word(word))

def recursive_sum(x):
  total=0
  for item in x:
    if isinstance (item,(list,tuple)):
      total+=recursive_sum(item)
    elif isinstance(item,(int,float)):
      total += item
  return total
print(recursive_sum([1,(2,3),[4,[5]]]))

import random
def weighted_choice(items,weights):
  total=sum(weights)
  r=random.uniform(0,total)
  upto=0
  for item,w in zip(items,weights):
    if upto+w>=r:
      return item
    upto+=w

print(weighted_choice(['a','b','c'],[1,2,3]))

from functools import lru_cache
@lru_cache(maxsize=32)
def fib(n):
    if n < 2: return n
    return fib(n-1)+fib(n-2)
print("Fib(20):", fib(20))

names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
zipped = list(zip(names, scores))
names2, scores2 = zip(*zipped)
print("Zipped:", zipped)
print("Unzipped names:", names2)
print("Unzipped scores:", scores2)

from pathlib import Path
p = Path("/home/user/docs/report.txt")
print_parent = p.parent
print_name = p.name
print_suffix = p.suffix
print("Parent:", print_parent)
print("Name:", print_name)
print("Suffix:", print_suffix)

def is_even(n):
    return n % 2 == 0
squares_even = [x*x for x in range(10) if is_even(x)]
print("Even squares:", squares_even)
print("Count:", len(squares_even))

def fibo(n):
  a,b=0,1
  for _ in range(n):
    yield a
    a,b=b,a+b
print(list(fibo(10)))

nums = [2,4,6,8,9]
print("All even?", all(n%2==0 for n in nums))
print("Any odd?", any(n%2==1 for n in nums))

def pairwise(ite):
  it=iter(ite)
  prev=next(it,None)
  for curr in it:
    yield prev,curr
    prev=curr
print(list(pairwise([1,2,3,4])))

def flatten(x):
    out = []
    for item in x:
        if isinstance(item, (list, tuple)):
            out.extend(flatten(item))
        else:
            out.append(item)
    return out

example = [1, (2,3), [4, [5,6], (7,)], 8]
print("Flattened:", flatten(example))

name = "Alice"
pi = 3.14159
print(f"Hello {name},pi appprox{pi:.2f}")

people = [{"name":"A","age":30},{"name":"B","age":25},{"name":"C","age":35}]
sorted_by_age = sorted(people, key=lambda p: p['age'])
print("Sorted:", sorted_by_age)