# -*- coding: utf-8 -*-
"""Python Code Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zG-ZdF38reRdRmWypdlPvsX02B85AOzi
"""

#Set Operations
#Example-1
x={10,20,30,40}
y={30,40,50,60}
print("Union:",x|y)

print("Intersection:",x&y)
print("Difference:",x-y)
print("Symmetric difference:",x^y)

#Example-2
names = ["Mim","Mim","Tim","Tim","Maisha","Luba"]
unique = set(names)
print("Original names (list):",names)
print("Unique names (set):",unique)



#Example-3
even ={n for n in range(12) if n%2 ==0}
print("Even number set:",even)



#example-4
name="Maisha"
unique_letters=set(name);
print("Unique Letters in 'Maisha':", unique_letters)



#example-5
x = {10, 20, 30}
y = {40, 50}
z = {10, 20}
print("X and Y disjoint?",x.isdisjoint(y))
print("Z subset of X?",z.issubset(x))
print("X superset of Z?",x.issuperset(z))

#example-6
numbers = {10, 20, 30, 40}
print("20 in numbers?->", 20 in numbers)
print("50 not in numbers?->", 50 not in numbers)

#example-7
colors = {"red","green","blue","yellow"}
print("Colors set:",colors)
print("Number of colors:",len(colors))

#example-8
course = {"Math","Physics"}
course.add("Chemistry")
course.discard("Math")
course.update(["Biology", "English"])
print("Final Course set:", course)

#example-9
id = {101, 102, 103}
roll = frozenset([103, 104, 105])
print("Union:", id|roll)
print("Intersection:",id&roll)
print("Difference:",id-roll)

#example-10
roll = frozenset([103, 104, 105])
print("Roll:",roll)
try:
   roll.remove(103)
except AttributeError as e:
  print("Error:",e)

#Tuple Operations

#example-1
a = (1, 2, 3)
print(a)
print(len(a))

#example-2
data = (5, 10, 15, 20)
print("Tuple:", data)
print("Second element:",data[1])
print("First element:",data[0])
print("Second last element:",data[-2])
print("last element:",data[-1])

#example-3
nums = (10, 20)
try:
    nums[1] = 50
except TypeError:
    print("Tuple is immutable")

#example-4
import math
a = (1, 2)
b = (4, 6)
d = math.dist(a, b)
print("Point A:", a)
print("Point B:", b)
print("Distance:", d)

#example-5
import math

point=((1,2),(3,4),(8,10))
def distance(a,b):
  return math.dist(a,b)
print("Points:",point)
print("Distance between two points:", distance(point[0], point[-1]))

#example-6
students=(("roll","name"),(101,"Mim"),(102,"Tim"))
head=students[0]
rows=students[1:]
print(head)
print(rows)
for r in rows:
  print(dict(zip(head,r)))

#example-7
nested =((1,2),(10,22,33),("Mango","yellow"))

def convert_into_tuple(t):
  out=[]
  for it in t:
    if isinstance(it,tuple):
      out.extend(convert_into_tuple(it))
    else:
      out.append(it)
  return tuple(out)

print("Nested Tuple:",nested);
print("Flattened tuple:",convert_into_tuple(nested))

#example-8
t = (10, 20, 30, 40, 50)
print("Slice:",t[3:5])
print("Middle:", t[1:4])
print("Reverse:", t[::-1])

#example-9
info = ("Rahim", 21, 5.6, True)
for x in info:
    print(x," : The type of this element is ->",type(x).__name__)

#example-10
info = ("Maisha", 21, "CSE")
name,age,dept = info
print(f"Name:{name},Age:{age},Department:{dept}")

#example-11
def operation(num):
  return(min(num),max(num),sum(num))
numbers=(10,20,30,40,50)
minimum, mximum, total = operation(numbers)
print(f"Min: {minimum}, Max: {mximum}, Sum: {total}")

#Dictionary Operations

#example-1
data = {"pen": 5, "book": 10}
inverse ={v:k for k,v in data.items()}
print(data)
print(inverse)

#example-2
student = {"roll":101, "dept":"CSE"}
print(student)
print(student["dept"])

#example-3
nums = [1, 2, 1, 3, 2, 1]
frequency={}
for it in nums:
  frequency[it] = frequency.get(it,0) +1
print(frequency)

#example-4
students={
    "A":{"mark":90,"grade":"A+"},
     "B":{"mark":80,"grade":"A+"}
}
for id,info in students.items():
  print(id,"-> Marks:",info["mark"],"Grade:",info["grade"])

#example-5
x = {"a": 10, "b": 20}
y = {"b": 30, "c": 40}
result = {**x, **y}
print(result)

#example-6
data = {"x": 1, "y": 2}
for k in data:
    print("Key:", k)

for v in data.values():
    print("Value:", v)

for k, v in data.items():
    print(k, "->", v)

#example-7
student = {"name": "Maisha"}
id = student.get("id",106)
student.setdefault("Dept","CSE")
print("Info:",student)
print("ID:",id)

#example-8
cubes = {x: x*x*x for x in range(4)}
print(cubes)

#example-9
scores = { "Luba": 88,"Maisha": 75, "sima": 92,"Afnan": 80}
sorted_by_key=dict(sorted(scores.items()))
sorted_by_value=dict(sorted(scores.items(), key=lambda x:x[1]))
print("Original:", scores)
print("Sorted by name:", sorted_by_key)
print("Sorted by marks:", sorted_by_value)

#example-10
info = {"name": "Maisha"}
info["age"] = 21
info["name"] = "Luba"
print(info)

#List operations

#Example-1
num=[[1,2],[3,4,[5,6]],7]
def flatten(lst):
  result=[]
  for it in lst:
    if isinstance(it ,list):
      result.extend(flatten(it))
    else:
      result.append(it)
  return result

print("Original:", num)
print("Flattened:", flatten(num))

#Example-2

#Example-3
data = [[1, 2], (3, [4, (5, 6)]), "x", ["y", ["z"]]]

def flatten(it):
    result = []
    for item in it:
        if isinstance(item, (list, tuple)):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

print("Original:", data)
print("Flattened:", flatten(data))

#Example-4
odds_square = [x*x for x in range(15) if x % 2 != 0]
print("Odd squares:", odds_square)

#Example-5
nums = [10, 20, 30, 40, 50, 60]
print("Original:", nums)
print(nums[1:4])
print("Every 3rd:",nums[::3])
print("Reversed:",nums[::-1])

#Example-6
points = [(1, 2), (5, 2), (5, 6), (1, 6)]
def center(points):
  x=[p[0] for p in points]
  y=[p[1] for p in points]
  return(sum(x)/len(x),sum(y)/len(y))

print("Points:", points)
print("Centroid:", center(points))

#Example-7
names = ["Mim", "Tim", "Luba"]
def join_with_coma(lst):
  return ", ".join(lst)

print(join_with_coma(names))

#Example-8
data = ["Rahim", 25, 5.9, False, None, [1, 2]]
def des(lst):
  return [(type(x).__name__,x) for x in lst]
print("Description:", des(data))

#Example-9
items = ["pen", "book", "pen", "book", "scale"]
def unique_item(lst):
  temp=set()
  out=[]
  for it in lst:
    if it not in temp :
      temp.add(it)
      out.append(it)
  return out

print("Original:", items)
print("Unique:", unique_item(items))

#Example-10
numbers = [1, 2, 3, 4, 5, 6, 7, 8]

def summ(lst):
    return sum(lst)

print("Numbers:", numbers)
print("Sum of numbers:", summ(numbers))

# #create function of management take input from user (name,age,dept,salary) for 5 person  and store those data in list

# def management():
#   person=[]
#   name=input("Name:")
#   age=int(input("Age:"))
#   dept=input("Dept:")
#   salary=int(input("salary:"))

#   persons ={name,age,dept,salary}
#   person.append(persons)
#   #return person
#   print(person)

#   #return f"Name:{name},Age:{age},Dept:{dept},Salary:{salary}"

# #management()
# for i in range(5):
#   management()

def management(name,age,dept,salary):
  return {"Name": name,"Age":age,"Dept":dept,"salary":salary}

info=[]

for i in range(3):
    name=input("Name:")
    age=int(input("Age:"))
    dept=input("Dept:")
    salary=int(input("salary:"))
    info.append(management(name,age,dept,salary))
info

def information(name,age,id,cgpa,home):
   return {"Name":name,"Age":age,"Id":id,"CGPA":cgpa,"Home":home}

details=[]
for i in range(1):
  name=input("Name:")
  age=int(input("Age:"))
  id=int(input("ID:"))
  cgpa=int(input("CGPA:"))
  home=input("Home:")
  if cgpa < 3.3:
     cgpa="Fail"
  details.append(information(name,age,id,cgpa,home))
print("Dtails of Students:")
details

info