# -*- coding: utf-8 -*-
"""Python Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wkq80AbKXXoChxmxXZ5bbMbZDVr2bY3
"""

population = [100000, 105000, 110000, 120000]
for i in range(1,len(population)):
  growth = population[i] - population[i-1]
  print("Year", i, "Growth:", growth)

routes = {
    "Route A": ["8:00", "10:00", "12:00"],
    "Route B": ["9:00", "11:00", "13:00"]
}
for route,times in routes.items():
  print(route)
  for t in times:
    print("  bus at",t)

rooms=[0]*5
requests=[1,2,2,4,3]
for r in requests:
  if rooms[r-1]==0:
    rooms[r-1]=1
    print("Room", r,"Booked")
  else:
    print("Room", r,"Already booked")

print("Room status:",rooms)

sales = {
    "Pen": [10, 12, 15, 9],
    "Notebook": [5, 7, 6, 8],
    "Bag": [2, 3, 4, 3]
}

for product, qtys in sales.items():
    total = 0
    for q in qtys:
        total += q
    print(product, "Total sold:", total)

temps = [
    [30, 32, 31, 33],
    [28, 29, 30, 31],
    [35, 36, 34, 33]
]
month=1
for week in temps:
  total=0
  for i in week:
    total+=i
  avg=total/len(week)
  print("Month", month, "Average Temp:", avg)
  month += 1

usage = [500, 750, 300, 900, 600]
limit = 3000

total = 0
for u in usage:
    total += u
    print("Used:", u, "MB | Total:", total)

if total > limit:
    print("Data limit exceeded")
else:
    print("Within limit")

units_list = [120, 250, 90, 310]
for unit in units_list:
  bill=0
  for u in range(1,unit+1):
    if u <= 100:
            bill += 2
    elif u <= 200:
        bill += 3
    else:
        bill += 5
  print("Units:",unit,"Bill:",bill)

student = {
    "Rahim": [80, 85, 90],
    "Karim": [60, 65, 70],
    "Ayesha": [90, 92, 95]
}
for name, scores in student.items():
    total = 0
    for s in scores:
        total += s
    avg = total / len(scores)

    if avg >= 85:
        grade = "Excellent"
    elif avg >= 70:
        grade = "Good"
    else:
        grade = "Needs Improvement"

    print(name, "Average:", avg, "Performance:", grade)

feedback = ["good", "bad", "excellent", "good", "bad", "good"]
summary = {}

for f in feedback:
    if f in summary:
        summary[f] += 1
    else:
        summary[f] = 1

for k, v in summary.items():
    print(k, ":", v)

classes = {
    "Class 1": [1,1,0,1],
    "Class 2": [0,1,1,1],
    "Class 3": [1,1,1,1]
}
for cls,data in classes.items():
  present=0
  for d in data:
    if d==1:
      present+=1
  print(cls, "Attendance:", present, "/", len(data))

students = {
    "Rahim": [1,1,1,0,1],
    "Karim": [1,0,0,0,1],
    "Ayesha": [1,1,1,1,1]
}

for name, progress in students.items():
    completed = 0
    for p in progress:
        if p == 1:
            completed += 1
    percent = (completed / len(progress)) * 100
    print(name, "Completion:", percent, "%")

monthly = [5000, -2000, 3000, -1000, 4000]
profit = 0
loss = 0
for m in monthly:
    if m > 0:
        profit += m
    else:
        loss += m

print("Total Profit:", profit)
print("Total Loss:", loss)

expenses = {
    "Monday": [50, 30, 20],
    "Tuesday": [60, 40],
    "Wednesday": [25, 35, 15]
}
weekly_total = 0
for day, costs in expenses.items():
    day_total = 0
    for c in costs:
        day_total += c
    weekly_total += day_total
    print(day, "Total Expense:", day_total)
print("Weekly Expense:", weekly_total)

attempts = ["java", "c++", "python"]
password = "c++"
count=0
correct=False
for a in attempts:
  count+=1
  if a==password:
    #print("Login successful")
    #break
    correct=True
    break

if correct==True:
   print("Login successful")
else:
   print("Wrong password")

if count == len(attempts):
      print("Access denied")

temps = [30, 32, 35, 33, 31, 29]
total = 0

for t in temps:
    total += t

avg = total / len(temps)

above_avg = []
for t in temps:
    if t > avg:
        above_avg.append(t)

print("Average:", avg)
print("Above average temps:", above_avg)

marks = [85, 72, 90, 60, 55]
grades = []
for m in marks:
    if m >= 80:
        grades.append("A")
    elif m >= 70:
        grades.append("B")
    elif m >= 60:
        grades.append("C")
    else:
        grades.append("F")

print("Grades:", grades)

courses = {
    "Python": ["A","B","C"],
    "ML": ["A","C"],
    "Data Science": ["B","C","D"]
}

for course, students in courses.items():
    print(course, "Total students:", len(students))
    for s in students:
        print("-", s)

cart = {
    "apple": 120,
    "banana": 40,
    "milk": 60,
    "bread": 50
}

total = 0
for item, price in cart.items():
    print(item, "price:", price)
    total += price

print("Total bill:", total)

employees = [
    {"name": "A", "salary": 30000},
    {"name": "B", "salary": 40000},
    {"name": "C", "salary": 50000}
]
for em in employees:
  if em["salary"]<40000:
    em["salary"] +=5000
  else:
    em["salary"] +=3000
for em in employees:
  print(em["name"],em["salary"])

correct_password = "admin123"
attempts = ["1234", "admin", "admin123"]
count = 0
got=False
for pwd in attempts:
    count += 1
    if pwd == correct_password:
      got=True
        #print("Login successful at attempt", count)
      break
if got==True:
  print("Login successful at attempt", count)
else:
  print("Wrong password")

if count > len(attempts):
    print("Account locked")

days_late = [0, 2, 5, 10]
fines = []

for d in days_late:
    fine = 0
    for day in range(1, d+1):
        fine += 2
    fines.append(fine)

print("Fines:", fines)

days_late = [0, 2, 5, 10]
fines = []
i = 0
for d in days_late:
   # x=2*days_late[i]
   # fines.append(x)
  days_late[i] =2*days_late[i]
  i+=1

#print("Fines:", fines)
print(days_late)

passwords = ["abc", "Admin123", "pass@123"]

for pwd in passwords:
    has_digit = False
    has_special = False
    for ch in pwd:
        if ch.isdigit():
            has_digit = True
        if not ch.isalnum():
            has_special = True

    if len(pwd) >= 6 and has_digit and has_special:
        print(pwd, "Strong")
    else:
        print(pwd, "Weak")

numbers = list(range(1, 51))
even = []
odd = []
div_by_five = []
for n in numbers:
    if n % 2 == 0:
        even.append(n)
    else:
        odd.append(n)

    if n % 5 == 0:
        div_by_five.append(n)
print("Even:", even)
print("Odd:", odd)
print("Divisible by 5:", div_by_five)

prime=[]
arr=list(range(2,51))
for num in arr:
  is_prime=True
  for i in range(2,num):
    if num%i==0:
      is_prime=False
      break
    if is_prime:
      prime.append(num)
print("Prime numbers:", prime)

transactions = [1000, -200, -300, 500, -100]
balance = 0
for t in transactions:
    balance += t
    print("Transaction:", t, "Balance:", balance)
print("Final Balance:", balance)

text = "Python123!"
letters = digits = special = 0

for ch in text:
    if ch.isalpha():
        letters += 1
    elif ch.isdigit():
        digits += 1
    else:
        special += 1

print("Letters:", letters)
print("Digits:", digits)
print("Special:", special)

secret = 15
guesses = [5, 10, 15, 20]
for g in guesses:
    if g < secret:
        print(g, "is too small")
    elif g > secret:
        print(g, "is too large")
    else:
        print("Correct guess:", g)
        break

i=1
while i<=3:
  j=1
  while j<=3:
    print(i,j)
    j+=1
  i+=1

numbers = [3, 6, 9, 12]
i=0
while i< len(numbers):
  print(numbers[i])
  i+=1

total = 0
for i in range(1, 51):
    if i % 2 == 0:
        total += i
print("Even Sum:", total)

num = 123456
count = 0
while num > 0:
    count += 1
    #num //= 10
    num=num//10
print("Digits:", count)

for i in range(1, 21):
    if i % 3 == 0:
        continue
    print(i)

nums = [1, 2, 3, 4]
squares = []
for n in nums:
    squares.append(n*n)
print(squares)
i=0
while i <len(nums):
  nums[i]=3*nums[i]
  i+=1
print(nums)

nums = [4, 7, 9, 2]
target = 9
found = False
found1=False
for n in nums:
    if n == target:
        found = True
        break
print("Found:", found)
i=0
while i <len(nums):
  nums[i]==target
  found1=True
  i+=1
print("Found1:", found1)

for i in range(1, 6):
    for j in range(1, i+1):
        print(j, end=" ")
    print()

text = "python is easy and python is powerful"
words = text.split()
freq = {}
print(words)
for w in words:
    if w in freq:
        freq[w] += 1
    else:
        freq[w] = 1

for k, v in freq.items():
    print(k, ":", v)

total = 0
for i in range(1, 51):
    if i % 2 != 0:
        total += i
print("Odd Sum:", total)

nums = [5, 12, 3, 21, 8]
max_val = nums[0]
for n in nums:
    if n > max_val:
        max_val = n
print("Max:", max_val)

a,b=0,1
for _ in range(10):
  print(a)
  a,b=b,a+b

num=1234
rev=0
while  num>0:
  #print(num%10)
  rev=rev*10+(num%10)
  num=num//10
print(rev)

for i in range(1, 6):
    print(" " * (5 - i) + "*" * (2*i - 1))

names = ["A", "B", "C"]
for index, name in enumerate(names):
    print(index, name)

matrix = [[1,2],[3,4]]
total = 0
for row in matrix:
    for val in row:
        total += val
print("Matrix Sum:", total)

colors = {"red", "green", "blue"}
for c in colors:
    print(c)

num = 121
temp = num
rev = 0
while temp > 0:
    rev = rev * 10 + temp % 10
    temp //= 10

if num == rev:
    print("Palindrome")
else:
    print("Not Palindrome")

nums = [5, 12, 3, 21, 8]
min_val = nums[0]
for n in nums:
    if n < min_val:
        min_val = n
print("Min:", min_val)

for i in range(10, 0, -1):
    print(i)

for i in range(1, 11):
    print("Number:", i)

for i in range(1, 21):
    if i % 2 != 0:
        print(i)

for i in range(1, 10):
    if i == 5:
        break
    print(i)

for i in range(1, 4):
    for j in range(1, 4):
        print(i, j)

for i in range(0, 21, 2):
    print(i)

student = {"name": "Rahim", "age": 20, "dept": "CSE"}
for key, value in student.items():
    print(key, ":", value)

nums = [1, 2, 3, 4, 5]
total = 0
for n in nums:
    total += n
print("Sum:", total)

n=5
fact=1
while n>0:
  fact=fact*n
  n=n-1
print(fact)

for i in range(1, 10):
    if i % 2 == 0:
        continue
    print(i)

n = 5
for i in range(1, 11):
    print(n, "x", i, "=", n*i)

for i in range(1, 6):
    print("*" * i)

secret = 7
for guess in range(1, 11):
    if guess == secret:
        print("Guessed correctly:", guess)
        break

fruits = ["apple", "banana", "mango"]
for fruit in fruits:
    print(fruit)

text = "python programming"
count = 0
for ch in text:
    if ch in "aeiou":
        count += 1
print("Vowels:", count)

nums = [10, 20, 30, 40]
i = 0
while i < len(nums):
    print(nums[i])
    i += 1

student = {"name": "Rahim", "age": 20, "dept": "CSE"}
for key, value in student.items():
    print(key, ":", value)

nums = [1, 2, 3, 4, 5]
total = 0
for n in nums:
    total += n
print("Sum:", total)

i = 1
while True:
    print(i)
    if i == 5:
        break
    i += 1